# Generated by Django 4.0.5 on 2022-06-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
